Correct spelling mistakes.
Python-Markdown/markdown pull request #623
Opened 2018-01-07 08:06 UTC by EdwardBetts

2018-01-07 21:56 UTC, waylan requested changes
Wow, that was a lot of misspelled words in places they would never bother me. I'm happy to accept the changes with a few exceptions. If you could make the requested changes, I'll be happy to accept this.

2018-01-07 21:56 UTC, waylan commented on tests/test_extensions.py
>                 '*[ABBR]: Abreviation'
If you are going to change the output, you also need to change the input or the test [fails](https://travis-ci.org/Python-Markdown/markdown/jobs/325987980#L591).

2018-01-07 21:56 UTC, waylan commented on tests/php/extra/Footnotes.text
> +	This footnote should appear even though as it is referred
The `php` test files are borrowed directly from the PHP project and should always remain unchanged. Please do not make any changes to these files. These changes need to be undone before I can accept this.

2018-01-07 21:56 UTC, waylan commented on tests/pl/Tests_2004/Markdown Documentation - Basics.html
> +interchangeable; this:</p>
The `pl` test files are borrowed directly from the Perl Markdown project and should always remain unchanged. Please do not make any changes to these files. These changes need to be undone before I can accept this.

2018-01-13 09:27 UTC, EdwardBetts commented
I've made the changes that you asked for. I ran the tests and they passed.

2018-01-13 16:42 UTC, waylan approved these changes

2018-01-13 16:42 UTC, merged