allow html as permalink
Python-Markdown/markdown pull request #771
Opened 2018-12-30 18:17 UTC by ggueret

I wanted to use a Font-Awesome icon as permalink for a project. So I defined TOC permalink as follows: `<i class="fas fa-link"></i>`. Currently, `TocTreeprocessor.add_permalink` treats permalink content as an `etree.Element` text, so the html tag will be escaped.

This patch aim to allows both text and html.

2018-12-30 18:27 UTC, waylan requested changes
Interesting idea. I'm not 100% sure we want to do this, but I can see the usefulness of it. What if we allowed custom classes to be assigned to the link itself instead?

Either way, this needs a test and a comment in the release notes before it can be accepted.

2019-01-08 19:18 UTC, waylan commented
Interesting change. By accepting a ElementTree object you eliminate the need to parse HTML, which can be problematic if invalid HTML is provided. However, I like this even less from a user's perspective. I still think the proper approach would be to simply add a `permalink_class` setting which defined a HTML class on the `<a>` tag for the permalink.

Then you could easily do `permalink_class="fas fa-link"`, which would give you:

    '<a class="fas fa-link" href="#header" title="Permanent link">&para;</a>'

I believe that would work fine with Font-Awesome's CSS.

Of course the default value of `permalink_class` would be `headerlink` to match the existing behavior.

2019-01-08 19:18 UTC, ggueret commented on markdown/extensions/toc.py
> +                if self.use_permalinks or isinstance(self.use_permalinks, etree.Element):
Needed extra check, because a `bool(etree.Element("a"))` will return False

2019-01-08 19:21 UTC, ggueret commented
Thanks @waylan, yeah, it makes a lot more sense to accept an `etree.Element` instance as a permalink value. I added a test and updated the toc doc.

2019-01-08 19:39 UTC, closed without merging

2019-01-10 03:29 UTC, ggueret commented
Closed because of irrelevant changes, continued in #776.