Simplify xml.etree.ElementTree loading
Python-Markdown/markdown pull request #902
Opened 2020-02-01 17:24 UTC by mitya57

cElementTree [is a deprecated alias for ElementTree][1] since Python 3.3. As we are now supporting only Python ≥ 3.5, we do not need to use it.

The version check is also no longer needed. The module has [version 1.3.0][2] since 2010, so even Python 2.7 and 3.2 have it (see python/cpython@f15351d938e76c4b).

[1]: https://docs.python.org/3/library/xml.etree.elementtree.html#module-xml.etree.ElementTree
[2]: https://bugs.python.org/issue6472

2020-02-01 19:17 UTC, waylan requested changes
Simplifying the code by removing old cruft like this is great. However, the cruft has only been half removed. See my comments below for what need sot happen before this can be accepted.

2020-02-01 19:17 UTC, waylan commented on markdown/util.py
> -    etree.test_comment = Comment
The [failing test][1] is caused by removing this line. The fix would be to update both the [tests][2] and the [serializer][3] to both use `from xml.etree.ElementTree.Comment` without the extra custom `test_comment` object.

[1]: https://travis-ci.org/Python-Markdown/markdown/jobs/644817928#L247
[2]: https://github.com/Python-Markdown/markdown/blob/master/tests/test_apis.py#L472-L515
[3]: https://github.com/Python-Markdown/markdown/blob/master/markdown/serializers.py#L45-L48

2020-02-01 19:17 UTC, waylan commented on markdown/util.py
>  # markdown.util import etree`).  Do not import it by yourself.
These comments should be rewritten as they are no longer correct. Instead, we would now be importing `etree` here for backward compatibility with old third party extensions which used to rely on our custom import.

However, as that custom import is no longer necessary, the `markdown` library itself should not use this import at `markdown.util` but simply import `tree` directly. Perhaps we could even raise a deprecation warning if third party code uses this import.

2020-02-01 19:17 UTC, waylan commented on markdown/util.py
> +import xml.etree.ElementTree as etree
This is getting [two flake8 errors][1]. Given the situation, those errors are acceptable. Therefore a comment needs to be added to this line to tell Flake8 to ignore the line: `# noqa`.

[1]: https://travis-ci.org/Python-Markdown/markdown/jobs/644817931#L242

2020-02-01 21:42 UTC, mitya57 commented
Now that we deprecated this, I had to update a lot of internal code. Commit 0f48d17e deprecates the old `markdown.util.etree` wrapper, commits 80729a3a and 8b1f49a1 make the replacements, and commit 3b7a55be updates the documentation.

2020-02-01 21:57 UTC, waylan reviewed
This looks good. However, one thing is bothering me. Sometimes we import `as etree` and other times we don't do the `as etree` bit. Lets be consistent throughout the lib.

2020-02-02 08:51 UTC, mitya57 commented
Ok. I decided to go with the `as etree` form as it is shorter and requires less changes throughout the code.

2020-02-02 13:32 UTC, waylan approved these changes

2020-02-02 13:35 UTC, waylan commented
We should probably add a note to the release notes informing extension devs that `markdown.util.etree` is deprecated and that they should import `xml.etree.ElementTree` directly. With that small change, I think this is ready to go. Nice work.

2020-02-02 21:33 UTC, mitya57 commented
Done in 01ca7399. Please check if the wording is fine.

2020-02-03 19:31 UTC, waylan commented
> Please check if the wording is fine.

It was pretty good. I made a few adjustments to the first sentence for consistency ("`some.module.path` module" requires the article "the" but if you leave out the word "module" then you also should leave out the article). The other changes were mostly additions which I probably wouldn't have bothered with if I wasn't already making changes.

2020-02-03 19:38 UTC, merged